---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: nodeport
  nodeport_port: 31111
  hostname: awx-demo.internal
  web_resource_requirements:
    requests:
      cpu: "0"
      memory: "0"
    limits:
      cpu: 500m
      memory: 1Gi
  task_resource_requirements:
    requests:
      cpu: "0"
      memory: "0"
    limits:
      cpu: 500m
      memory: 1Gi
  ee_resource_requirements:
    requests:
      cpu: "0"
      memory: "0"
    limits:
      cpu: 500m
      memory: 1Gi
